<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class AnalyticsEventsForTawktoChat {
	private $analytics_events_for_tawkto_chat_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'analytics_events_for_tawkto_chat_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'analytics_events_for_tawkto_chat_page_init' ) );
	}

	public function analytics_events_for_tawkto_chat_add_plugin_page() {
		add_options_page(
			'Analytics Events for Tawkto Chat Configuration', // page_title
			'Tawkto Chat Analytics', // menu_title
			'manage_options', // capability
			'analytics-events-for-tawkto-chat', // menu_slug
			array( $this, 'analytics_events_for_tawkto_chat_create_admin_page' ) // function
		);
	}

	public function analytics_events_for_tawkto_chat_create_admin_page() {
		$this->analytics_events_for_tawkto_chat_options = get_option( 'analytics_events_for_tawkto_chat_option_name' ); ?>

		<div class="wrap">
			<h2Analytics Events for Tawkto Chat Configuration</h2>
			<p>text at the top of the page</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'analytics_events_for_tawkto_chat_option_group' );
					do_settings_sections( 'analytics-events-for-tawkto-chat-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function analytics_events_for_tawkto_chat_page_init() {
		register_setting(
			'analytics_events_for_tawkto_chat_option_group', // option_group
			'analytics_events_for_tawkto_chat_option_name', // option_name
			array( $this, 'analytics_events_for_tawkto_chat_sanitize' ) // sanitize_callback
		);


		add_settings_section(
			'analytics_events_for_tawkto_chat_setting_section_ongoing', // id
			'Ongoing Chat event', // title
			array( $this, 'analytics_events_for_tawkto_chat_section_info' ), // callback
			'analytics-events-for-tawkto-chat-admin' // page
		);

		add_settings_field(
			'enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0', // id
			'Enable sending Event when Chat is OnGoing for XX seconds', // title
			array( $this, 'enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0_callback' ), // callback
			'analytics-events-for-tawkto-chat-admin', // page
			'analytics_events_for_tawkto_chat_setting_section_ongoing' // section
		);

		add_settings_field(
			'minimum_chat_duration_for_trigger_the_event_1', // id
			'Minimum Chat duration for trigger the event', // title
			array( $this, 'minimum_chat_duration_for_trigger_the_event_1_callback' ), // callback
			'analytics-events-for-tawkto-chat-admin', // page
			'analytics_events_for_tawkto_chat_setting_section_ongoing' // section
		);

		add_settings_field(
			'analytics_event_category_for_ongoing_2', // id
			'Analytics Event Category for Ongoing', // title
			array( $this, 'analytics_event_category_for_ongoing_2_callback' ), // callback
			'analytics-events-for-tawkto-chat-admin', // page
			'analytics_events_for_tawkto_chat_setting_section_ongoing' // section
		);

		add_settings_field(
			'analytics_event_action_for_ongoing_3', // id
			'Analytics Event Action for Ongoing', // title
			array( $this, 'analytics_event_action_for_ongoing_3_callback' ), // callback
			'analytics-events-for-tawkto-chat-admin', // page
			'analytics_events_for_tawkto_chat_setting_section_ongoing' // section
		);

		add_settings_section(
			'analytics_events_for_tawkto_chat_setting_section_offline', // id
			'Offline Chat event', // title
			array( $this, 'analytics_events_for_tawkto_chat_section_info' ), // callback
			'analytics-events-for-tawkto-chat-admin' // page
		);

		add_settings_field(
			'enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4', // id
			'Enable sending Event when a form from an offline Chat is submitted', // title
			array( $this, 'enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4_callback' ), // callback
			'analytics-events-for-tawkto-chat-admin', // page
			'analytics_events_for_tawkto_chat_setting_section_offline' // section
		);

		add_settings_field(
			'analytics_event_category_for_offline_5', // id
			'Analytics Event Category for Offline', // title
			array( $this, 'analytics_event_category_for_offline_5_callback' ), // callback
			'analytics-events-for-tawkto-chat-admin', // page
			'analytics_events_for_tawkto_chat_setting_section_offline' // section
		);

		add_settings_field(
			'analytics_event_action_for_offline_6', // id
			'Analytics Event Action for Offline', // title
			array( $this, 'analytics_event_action_for_offline_6_callback' ), // callback
			'analytics-events-for-tawkto-chat-admin', // page
			'analytics_events_for_tawkto_chat_setting_section_offline' // section
		);
	}

	public function analytics_events_for_tawkto_chat_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0'] ) ) {
			$sanitary_values['enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0'] = $input['enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0'];
		}

		if ( isset( $input['minimum_chat_duration_for_trigger_the_event_1'] ) ) {
			$sanitary_values['minimum_chat_duration_for_trigger_the_event_1'] = sanitize_text_field( $input['minimum_chat_duration_for_trigger_the_event_1'] );
		}

		if ( isset( $input['analytics_event_category_for_ongoing_2'] ) ) {
			$sanitary_values['analytics_event_category_for_ongoing_2'] = sanitize_text_field( $input['analytics_event_category_for_ongoing_2'] );
		}

		if ( isset( $input['analytics_event_action_for_ongoing_3'] ) ) {
			$sanitary_values['analytics_event_action_for_ongoing_3'] = sanitize_text_field( $input['analytics_event_action_for_ongoing_3'] );
		}

		if ( isset( $input['enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4'] ) ) {
			$sanitary_values['enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4'] = $input['enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4'];
		}

		if ( isset( $input['analytics_event_category_for_offline_5'] ) ) {
			$sanitary_values['analytics_event_category_for_offline_5'] = sanitize_text_field( $input['analytics_event_category_for_offline_5'] );
		}

		if ( isset( $input['analytics_event_action_for_offline_6'] ) ) {
			$sanitary_values['analytics_event_action_for_offline_6'] = sanitize_text_field( $input['analytics_event_action_for_offline_6'] );
		}

		return $sanitary_values;
	}

	public function analytics_events_for_tawkto_chat_section_info() {

	}

	public function enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0_callback() {
		printf(
			'<input type="checkbox" name="analytics_events_for_tawkto_chat_option_name[enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0]" id="enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0" value="1" %s>',
			( isset( $this->analytics_events_for_tawkto_chat_options['enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0'] ) && $this->analytics_events_for_tawkto_chat_options['enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0'] == '1' ) ? 'checked' : ''
		);
	}

	public function minimum_chat_duration_for_trigger_the_event_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="analytics_events_for_tawkto_chat_option_name[minimum_chat_duration_for_trigger_the_event_1]" id="minimum_chat_duration_for_trigger_the_event_1" value="%s">',
			isset( $this->analytics_events_for_tawkto_chat_options['minimum_chat_duration_for_trigger_the_event_1'] ) ? esc_attr( $this->analytics_events_for_tawkto_chat_options['minimum_chat_duration_for_trigger_the_event_1']) : ''
		);
	}

	public function analytics_event_category_for_ongoing_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="analytics_events_for_tawkto_chat_option_name[analytics_event_category_for_ongoing_2]" id="analytics_event_category_for_ongoing_2" value="%s">',
			isset( $this->analytics_events_for_tawkto_chat_options['analytics_event_category_for_ongoing_2'] ) ? esc_attr( $this->analytics_events_for_tawkto_chat_options['analytics_event_category_for_ongoing_2']) : ''
		);
	}

	public function analytics_event_action_for_ongoing_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="analytics_events_for_tawkto_chat_option_name[analytics_event_action_for_ongoing_3]" id="analytics_event_action_for_ongoing_3" value="%s">',
			isset( $this->analytics_events_for_tawkto_chat_options['analytics_event_action_for_ongoing_3'] ) ? esc_attr( $this->analytics_events_for_tawkto_chat_options['analytics_event_action_for_ongoing_3']) : ''
		);
	}

	public function enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4_callback() {
		printf(
			'<input type="checkbox" name="analytics_events_for_tawkto_chat_option_name[enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4]" id="enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4" value="1" %s>',
			( isset( $this->analytics_events_for_tawkto_chat_options['enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4'] ) && $this->analytics_events_for_tawkto_chat_options['enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4'] == '1' ) ? 'checked' : ''
		);
	}

	public function analytics_event_category_for_offline_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="analytics_events_for_tawkto_chat_option_name[analytics_event_category_for_offline_5]" id="analytics_event_category_for_offline_5" value="%s">',
			isset( $this->analytics_events_for_tawkto_chat_options['analytics_event_category_for_offline_5'] ) ? esc_attr( $this->analytics_events_for_tawkto_chat_options['analytics_event_category_for_offline_5']) : ''
		);
	}

	public function analytics_event_action_for_offline_6_callback() {
		printf(
			'<input class="regular-text" type="text" name="analytics_events_for_tawkto_chat_option_name[analytics_event_action_for_offline_6]" id="analytics_event_action_for_offline_6" value="%s">',
			isset( $this->analytics_events_for_tawkto_chat_options['analytics_event_action_for_offline_6'] ) ? esc_attr( $this->analytics_events_for_tawkto_chat_options['analytics_event_action_for_offline_6']) : ''
		);
	}

}
if ( is_admin() )
	$analytics_events_for_tawkto_chat = new AnalyticsEventsForTawktoChat();

/*
 * Retrieve this value with:
 * $analytics_events_for_tawkto_chat_options = get_option( 'analytics_events_for_tawkto_chat_option_name' ); // Array of All Options
 * $enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0 = $analytics_events_for_tawkto_chat_options['enable_sending_event_when_chat_is_ongoing_for_xx_seconds_0']; // Enable sending Event when Chat is OnGoing for XX seconds
 * $minimum_chat_duration_for_trigger_the_event_1 = $analytics_events_for_tawkto_chat_options['minimum_chat_duration_for_trigger_the_event_1']; // Minimum Chat duration for trigger the event
 * $analytics_event_category_for_ongoing_2 = $analytics_events_for_tawkto_chat_options['analytics_event_category_for_ongoing_2']; // Analytics Event Category for Ongoing
 * $analytics_event_action_for_ongoing_3 = $analytics_events_for_tawkto_chat_options['analytics_event_action_for_ongoing_3']; // Analytics Event Action for Ongoing
 * $enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4 = $analytics_events_for_tawkto_chat_options['enable_sending_event_when_a_form_from_an_offline_chat_is_submitted_4']; // Enable sending Event when a form from an offline Chat is submitted
 * $analytics_event_category_for_offline_5 = $analytics_events_for_tawkto_chat_options['analytics_event_category_for_offline_5']; // Analytics Event Category for Offline
 * $analytics_event_action_for_offline_6 = $analytics_events_for_tawkto_chat_options['analytics_event_action_for_offline_6']; // Analytics Event Action for Offline
 */
